#!/bin/bash

echo ==============================================================================================
echo - Open ports 80 and 443 on your firewall needed for certificate creation and http redirect
echo - Create an A record for you domain and point it to the IP of this server - $(wget -qO- http://ipecho.net/plain)
echo ==============================================================================================
read -p "press enter to continue"

echo getting ready
apt install -y dnsutils > /dev/null 2>&1

echo Domain Name: ; read domainname ; export domainname

if [[ $(dig $domainname +short) = $(wget -qO- http://ipecho.net/plain) ]]
then
 echo $domainname A record matches this server IP
else
 echo ERROR! $domainname A record does not match this server IP
 exit 1
fi

echo Email Address: ; read emailaddress ; export emailaddress
echo MariaDB root Password: ; read dbrootpass ; export dbrootpass

dbname=$(echo $domainname | sed -e 's/\.//g') ; export dbname
dbuser=$(echo $domainname | sed -e 's/\.//g') ; export dbuser
dbpass=$(echo $domainname | sed -e 's/\.//g') ; export dbpass

echo update
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/02_install_updates)

echo install prerequisites
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/03_install_prerequisites)

echo install docker
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/04_install_docker)

echo install portainer
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/05_install_portainer)

echo install mariadb
wget -q https://raw.githubusercontent.com/aristosv/webserver/main/06_install_mariadb --output-document="/tmp/mariadb"
sed -i "s/\$dbrootpass/$dbrootpass/g" /tmp/mariadb
sed -i "s/\$dbname/$dbname/g" /tmp/mariadb
sed -i "s/\$dbuser/$dbuser/g" /tmp/mariadb
sed -i "s/\$dbpass/$dbpass/g" /tmp/mariadb
chmod +x /tmp/mariadb
/tmp/mariadb
rm /tmp/mariadb

echo install phpmyadmin
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/07_install_phpmyadmin)

echo install swag
wget -q https://raw.githubusercontent.com/aristosv/webserver/main/08_install_swag --output-document="/tmp/swag"
sed -i "s/\$domainname/$domainname/g" /tmp/swag
sed -i "s/\$emailaddress/$emailaddress/g" /tmp/swag
chmod +x /tmp/swag
/tmp/swag
#rm /tmp/swag

echo install wordpress
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/09_install_wordpress)

echo install complete
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/webserver/main/10_install_complete)
