#!/bin/bash

echo installing mariadb
docker pull lscr.io/linuxserver/mariadb > /dev/null 2>&1
docker run -d \
 --restart=always \
 --name mariadb \
 -h mariadb \
 -e PUID=1001 \
 -e PGID=1001 \
 -e MYSQL_ROOT_PASSWORD=$dbrootpass \
 --net=network \
 -p 3306:3306 \
 -v mariadb:/config \
 lscr.io/linuxserver/mariadb > /dev/null 2>&1

echo waiting for mariadb to start
while ! docker exec mariadb mysql --user=root --password=$dbrootpass -e "SELECT 1" >/dev/null 2>&1 ; do sleep 1 ; done

echo creating database $dbname
docker exec mariadb mysql --user=root --password=$dbrootpass -e "CREATE DATABASE $dbname;"

echo creating user $dbuser
docker exec mariadb mysql --user=root --password=$dbrootpass -e "CREATE USER '$dbuser'@localhost IDENTIFIED BY '$dbpass';"

echo assigning privileges for user $dbuser to database $dbname
docker exec mariadb mysql --user=root --password=$dbrootpass -e "GRANT ALL ON $dbname.* TO '$dbuser'@localhost IDENTIFIED BY '$dbpass' WITH GRANT OPTION;"

echo flushing privileges
docker exec mariadb mysql --user=root --password=$dbrootpass -e "FLUSH PRIVILEGES;"
