#!/bin/bash

echo installing swag
docker pull lscr.io/linuxserver/swag > /dev/null 2>&1
docker run -d \
 --restart always \
 --name=swag \
 -h swag \
 --net=network \
 -p 80:80 \
 -p 443:443 \
 --cap-add=NET_ADMIN \
 -e PUID=1001 \
 -e PGID=1001 \
 -e URL=$domainname \
 -e SUBDOMAINS=www, \
 -e VALIDATION=http \
 -e EMAIL=$emailaddress \
 -e STAGING=false \
 -e EXTRA_DOMAINS=\
 -v swag:/config \
 lscr.io/linuxserver/swag > /dev/null 2>&1
 
echo waiting for swag to start
until $(curl --output /dev/null --silent --head --fail http://$(hostname -I | cut -d' ' -f1)) ; do sleep 1 ; done

echo creating $domainname configuration
cp /var/lib/docker/volumes/swag/_data/nginx/site-confs/default /var/lib/docker/volumes/swag/_data/nginx/site-confs/$domainname

echo modifying $domainname configuration
echo removing default server
sed -i -e "s| default_server||g" /var/lib/docker/volumes/swag/_data/nginx/site-confs/$domainname

echo configuring cache
sed -i -e "s|cache/|cache/$domainname|g" /var/lib/docker/volumes/swag/_data/nginx/site-confs/$domainname
sed -i -e "s|auth_cache|auth_cache_$domainname|g" /var/lib/docker/volumes/swag/_data/nginx/site-confs/$domainname

echo configuring html directory
sed -i -e "s|/config/www|/config/www/$domainname/html|g" /var/lib/docker/volumes/swag/_data/nginx/site-confs/$domainname

echo configuring server name
sed -i -e "s|server_name _|server_name $domainname www.$domainname|g" /var/lib/docker/volumes/swag/_data/nginx/site-confs/$domainname

echo creating $domainname directory
mkdir -p /var/lib/docker/volumes/swag/_data/www/$domainname/html

echo restarting swag
docker container restart swag > /dev/null 2>&1
