#!/bin/bash

echo downloading wordpress
wget -q https://wordpress.org/latest.zip --output-document="/tmp/latest.zip"

echo extracting wordpress
unzip -qq /tmp/latest.zip -d /tmp

echo moving wordpress to $domainname
mv /tmp/wordpress/* /var/lib/docker/volumes/swag/_data/www/$domainname/html

echo cleaning up
rm /tmp/latest.zip
rmdir /tmp/wordpress
