#!/bin/bash

echo 
echo MAKE A NOTE OF THIS INFORMATION
echo =====================================================
echo You can visit https://$domainname and setup WordPress
echo Database Name: $dbname
echo Username: $dbuser
echo Password: $dbpass
echo Database Host: mariadb
echo =====================================================
echo You can manage your database using phpMyAdmin
echo URL: http://$(hostname -I | cut -d' ' -f1):8082
echo Server: $(hostname -I | cut -d' ' -f1)
echo Username: root
echo Password: $dbrootpass
echo =====================================================
echo You can manage all your containers with Portainer
echo URL: http://$(hostname -I | cut -d' ' -f1):9000
echo =====================================================
