#!/bin/bash

echo installing portainer
docker pull portainer/portainer-ce > /dev/null 2>&1
docker run -d \
 --restart=always \
 --name portainer_data \
 -h portainer \
 -e PUID=1001 \
 -e PGID=1001 \
 -e TZ=Europe/Nicosia \
 -p 9000:9000 \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v portainer_data:/data \
 portainer/portainer-ce > /dev/null 2>&1
