#!/bin/bash

echo installing mariadb
docker pull lscr.io/linuxserver/mariadb > /dev/null 2>&1
docker run -d \
 --restart=always \
 --name mariadb \
 -h mariadb \
 -e PUID=1001 \
 -e PGID=1001 \
 -e MYSQL_ROOT_PASSWORD=$dbrootpass \
 --net=network \
 -p 3306:3306 \
 -v mariadb:/config \
 lscr.io/linuxserver/mariadb > /dev/null 2>&1

echo wating for mariadb to start
until [ "`docker inspect -f {{.State.Running}} mariadb`"=="true" ]; do
    sleep 0.1;
done;

echo creating database $dbname
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='CREATE DATABASE $dbname;'"

echo creating user $dbuser
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='CREATE USER '$dbuser'@'localhost' IDENTIFIED BY '$dbpass';'"

echo assigning privileges for user $dbuser to database $dbname
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='GRANT ALL ON $dbname.* TO '$dbuser'@'localhost' IDENTIFIED BY '$dbpass' WITH GRANT OPTION;'"

echo flushing privileges
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='FLUSH PRIVILEGES;'"
