#!/bin/bash

echo installing mariadb
docker pull lscr.io/linuxserver/mariadb > /dev/null 2>&1
docker run -d \
 --restart=always \
 --name mariadb \
 -h mariadb \
 -e PUID=1001 \
 -e PGID=1001 \
 -e MYSQL_ROOT_PASSWORD=$dbpass \
 --net=network \
 -p 3306:3306 \
 -v mariadb:/config \
 lscr.io/linuxserver/mariadb > /dev/null 2>&1

echo creating database $dbname
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbpass' --execute='CREATE DATABASE $dbname;'"
