#!/bin/bash

docker pull ghcr.io/linuxserver/phpmyadmin
docker run -d \
 --restart=always \
 --name phpmyadmin \
 -h phpmyadmin \
 -e PUID=1001 \
 -e PGID=1001 \
 -e PMA_ARBITRARY=1 \
 --net=network \
 -p 8082:80 \
 -v phpmyadmin:/config \
 ghcr.io/linuxserver/phpmyadmin
